/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Input_Output;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        Assertions.assertNotNull("app should have a greeting", "app should have a greeting");
    }
}
